{% set name = "napari-proofread-brainbow" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-proofread-brainbow-{{ version }}.tar.gz
  sha256: 2093bc0736413cdbc4dfc2a08fa3aa206b73f6027ca2f49d4d77b2b7478557d2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - napari_proofread_brainbow
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-proofread-brainbow/
  summary: proofreading Brainbow images with napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
